In [2]:
import pandas as pd
reviews=pd.read_csv(r"C:\Users\gokul\Downloads\xdm\datasample\wine-reviews\winemag-data-130k-v2.csv",index_col=0)
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [3]:
median_points = reviews.points.median()
median_points

88.0

In [4]:
countries = reviews['country'].unique()
countries

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', nan, 'Turkey', 'Czech Republic', 'Slovenia',
       'Luxembourg', 'Croatia', 'Georgia', 'Uruguay', 'England',
       'Lebanon', 'Serbia', 'Brazil', 'Moldova', 'Morocco', 'Peru',
       'India', 'Bulgaria', 'Cyprus', 'Armenia', 'Switzerland',
       'Bosnia and Herzegovina', 'Ukraine', 'Slovakia', 'Macedonia',
       'China', 'Egypt'], dtype=object)

In [5]:
reviews_per_country = reviews['country'].value_counts()
reviews_per_country

US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Serbia                       12
Czech Republic               12
Macedonia                    12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Bosnia and Herzegovina        2
Armenia                       2
China                         1
Slovakia                      1
Egypt                         1
Name: country, dtype: int64

In [8]:
review_price_mean = reviews.price.mean()
%timeit centered_price = reviews['price'].map(lambda p: p-review_price_mean)
centered_price

37.3 ms ± 526 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

0               NaN
1        -20.363389
2        -21.363389
3        -22.363389
4         29.636611
            ...
129966    -7.363389
129967    39.636611
129968    -5.363389
129969    -3.363389
129970   -14.363389
Name: price, Length: 129971, dtype: float64

In [9]:
%timeit centered_price = reviews.price - reviews.price.mean()
centered_price

737 µs ± 44.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

0               NaN
1        -20.363389
2        -21.363389
3        -22.363389
4         29.636611
            ...
129966    -7.363389
129967    39.636611
129968    -5.363389
129969    -3.363389
129970   -14.363389
Name: price, Length: 129971, dtype: float64

In [10]:
bargain_wine = reviews['points']/reviews['price']

In [11]:
bargain_wine

0              NaN
1         5.800000
2         6.214286
3         6.692308
4         1.338462
            ...
129966    3.214286
129967    1.200000
129968    3.000000
129969    2.812500
129970    4.285714
Length: 129971, dtype: float64

In [12]:
def points_price_ratio(row):
    row = row.points / row.price
    return row

id_max_ratio=reviews.apply(points_price_ratio, axis='columns').idxmax()

bargain_wine= reviews.loc[id_max_ratio,'title']
bargain_wine

'Bandit NV Merlot (California)'

In [13]:
bargain_idx = (reviews.points / reviews.price).idxmax()
bargain_wine = reviews.loc[bargain_idx, 'title']
bargain_wine

'Bandit NV Merlot (California)'

In [14]:
def contain_str(row):
    if row.find('tropical')!=-1:
        return 'tropical'
    elif row.find('fruity')!=-1:
        return 'fruity'
    else:
        return row

# a="This is ripe and fruity, a wine that is smooth while still structured. Firm tannins are filled out with juicy red berry fruits and freshened with acidity. It's  already drinkable, although it will certainly be better from 2016.  "
# print(contain_str(a))
# tropical
# fruity

descriptor_counts = reviews['description'].head()#.apply(contain_str, axis='columns).value_counts()
descriptor_counts

0    Aromas include tropical fruit, broom, brimston...
1    This is ripe and fruity, a wine that is smooth...
2    Tart and snappy, the flavors of lime flesh and...
3    Pineapple rind, lemon pith and orange blossom ...
4    Much like the regular bottling from 2012, this...
Name: description, dtype: object

In [15]:
n_trop = reviews.description.map(lambda desc: "tropical" in desc).sum()
n_fruity = reviews.description.map(lambda desc: "fruity" in desc).sum()
descriptor_counts1 = pd.Series([n_trop, n_fruity], index=['tropical', 'fruity'])
print(descriptor_counts1.shape)
descriptor_counts1

(2,)

tropical    3607
fruity      9090
dtype: int64

In [16]:
descriptor_counts1 = pd.DataFrame({'Count':[n_trop, n_fruity]}, index=['tropical', 'fruity'])
print(descriptor_counts1.shape)
descriptor_counts1

(2, 1)

          Count
tropical   3607
fruity     9090

In [17]:
reviews.description.map(lambda desc: "tropical" in desc).value_counts()

False    126364
True       3607
Name: description, dtype: int64

In [18]:
reviews.description.map(lambda desc: "fruity" in desc).value_counts()

False    120881
True       9090
Name: description, dtype: int64

In [19]:
def get_star_rating(row):
    if row.country == 'Canada':
        return 3
    elif row.points >= 95:
        return 3
    elif row.points >= 85:
        return 2
    else:
        return 1


star_ratings = reviews.apply(get_star_rating, axis='columns')
# print(star_ratings)
star_ratings

0         2
1         2
2         2
3         2
4         2
         ..
129966    2
129967    2
129968    2
129969    2
129970    2
Length: 129971, dtype: int64

In [20]:
reviews.groupby('points').points.count()

points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: points, dtype: int64

In [21]:
print(reviews.groupby('points').points)
reviews.groupby('points')

<pandas.core.groupby.generic.SeriesGroupBy object at 0x000001D71C8F3B70>

In [22]:
reviews.groupby('points').price.min()

points
80      5.0
81      5.0
82      4.0
83      4.0
84      4.0
85      4.0
86      4.0
87      5.0
88      6.0
89      7.0
90      8.0
91      7.0
92     11.0
93     12.0
94     13.0
95     20.0
96     20.0
97     35.0
98     50.0
99     44.0
100    80.0
Name: price, dtype: float64

In [23]:
# way of selecting the name of the first wine reviewed from each winery in the dataset
reviews.groupby('winery').apply(lambda df: df.title.iloc[0])

winery
1+1=3                                     1+1=3 NV Rosé Sparkling (Cava)
10 Knots                            10 Knots 2010 Viognier (Paso Robles)
100 Percent Wine              100 Percent Wine 2015 Moscato (California)
1000 Stories           1000 Stories 2013 Bourbon Barrel Aged Zinfande...
1070 Green                  1070 Green 2011 Sauvignon Blanc (Rutherford)
                                             ...
Órale                       Órale 2011 Cabronita Red (Santa Ynez Valley)
Öko                    Öko 2013 Made With Organically Grown Grapes Ma...
Ökonomierat Rebholz    Ökonomierat Rebholz 2007 Von Rotliegenden Spät...
àMaurice               àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                                    Štoka 2009 Izbrani Teran (Kras)
Length: 16757, dtype: object

In [24]:
# way of selecting the name of the first wine reviewed from each winery in the dataset
reviews.groupby('winery').apply(lambda df: df.title)

winery
1+1=3     20319                        1+1=3 NV Rosé Sparkling (Cava)
          33657     1+1=3 NV Cygnus Brut Nature Reserva Made With ...
          55163                        1+1=3 NV Brut Sparkling (Cava)
          56109     1+1=3 NV Cygnus Brut Nature Reserva Made With ...
          63807          1+1=3 2008 Rosé Cabernet Sauvignon (Penedès)
                                          ...
àMaurice  124544           àMaurice 2009 Syrah (Columbia Valley (WA))
          128023       àMaurice NV Pour Me Red (Columbia Valley (WA))
Štoka     10290                       Štoka 2009 Izbrani Teran (Kras)
          70504                    Štoka 2011 Grganja Vitovska (Kras)
          70505                       Štoka 2011 Izbrani Teran (Kras)
Name: title, Length: 129971, dtype: object

In [25]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [26]:
# pick out the best wine by country and province
reviews.groupby(['country', 'province']).apply(lambda df: df.loc[df.points.idxmax()])

                              country  \
country   province
Argentina Mendoza Province  Argentina
          Other             Argentina
Armenia   Armenia             Armenia
Australia Australia Other   Australia
          New South Wales   Australia
...                               ...
Uruguay   Juanico             Uruguay
          Montevideo          Uruguay
          Progreso            Uruguay
          San Jose            Uruguay
          Uruguay             Uruguay

                                                                  description  \
country   province
Argentina Mendoza Province  If the color doesn't tell the full story, the ...
          Other             Take note, this could be the best wine Colomé ...
Armenia   Armenia           Deep salmon in color, this wine offers a bouqu...
Australia Australia Other   Writes the book on how to make a wine filled w...
          New South Wales   De Bortoli's Noble One is as good as ever in 2...
...                                                                       ...
Uruguay   Juanico           This mature Bordeaux-style blend is earthy on ...
          Montevideo        A rich, heady bouquet offers aromas of blackbe...
          Progreso          Rusty in color but deep and complex in nature,...
          San Jose          Baked, sweet, heavy aromas turn earthy with ti...
          Uruguay           Cherry and berry aromas are ripe, healthy and ...

                                                        designation  points  \
country   province
Argentina Mendoza Province                         Nicasia Vineyard      97
          Other                                             Reserva      95
Armenia   Armenia                                    Estate Bottled      88
Australia Australia Other                             Sarah's Blend      93
          New South Wales                        Noble One Bortytis      94
...                                                             ...     ...
Uruguay   Juanico                  Preludio Barrel Select Lote N 77      90
          Montevideo        Monte Vide Eu Tannat-Merlot-Tempranillo      91
          Progreso                   Etxe Oneko Fortified Sweet Red      90
          San Jose                         El Preciado Gran Reserva      87
          Uruguay                         Blend 002 Limited Edition      91

                            price          province                 region_1  \
country   province
Argentina Mendoza Province  120.0  Mendoza Province                  Mendoza
          Other              90.0             Other                    Salta
Armenia   Armenia            15.0           Armenia                      NaN
Australia Australia Other    15.0   Australia Other  South Eastern Australia
          New South Wales    32.0   New South Wales          New South Wales
...                           ...               ...                      ...
Uruguay   Juanico            45.0           Juanico                      NaN
          Montevideo         60.0        Montevideo                      NaN
          Progreso           46.0          Progreso                      NaN
          San Jose           50.0          San Jose                      NaN
          Uruguay            22.0           Uruguay                      NaN

                           region_2        taster_name taster_twitter_handle  \
country   province
Argentina Mendoza Province      NaN  Michael Schachner           @wineschach
          Other                 NaN  Michael Schachner           @wineschach
Armenia   Armenia               NaN      Mike DeSimone        @worldwineguys
Australia Australia Other       NaN                NaN                   NaN
          New South Wales       NaN     Joe Czerwinski                @JoeCz
...                             ...                ...                   ...
Uruguay   Juanico               NaN  Michael Schachner           @wineschach
          Montevideo            NaN  Michael Schachner           @wineschach
          Progreso              NaN  Michael Schachner           @wineschach
          San Jose              NaN  Michael Schachner           @wineschach
          Uruguay               NaN  Michael Schachner           @wineschach

                                                                        title  \
country   province
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
          Other                            Colomé 2010 Reserva Malbec (Salta)
Armenia   Armenia                 Van Ardi 2015 Estate Bottled Rosé (Armenia)
Australia Australia Other   Marquis Philips 2000 Sarah's Blend Red (South ...
          New South Wales   De Bortoli 2007 Noble One Bortytis Semillon (N...
...                                                                       ...
Uruguay   Juanico           Familia Deicas 2004 Preludio Barrel Select Lot...
          Montevideo        Bouza 2015 Monte Vide Eu Tannat-Merlot-Tempran...
          Progreso          Pisano 2007 Etxe Oneko Fortified Sweet Red Tan...
          San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...

                                          variety                winery
country   province
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata
          Other                            Malbec                Colomé
Armenia   Armenia                            Rosé              Van Ardi
Australia Australia Other               Red Blend       Marquis Philips
          New South Wales                Sémillon            De Bortoli
...                                           ...                   ...
Uruguay   Juanico                       Red Blend        Familia Deicas
          Montevideo                    Red Blend                 Bouza
          Progreso                         Tannat                Pisano
          San Jose                      Red Blend        Castillo Viejo
          Uruguay           Tannat-Cabernet Franc               Narbona

[425 rows x 13 columns]

In [27]:
reviews.groupby(['country', 'province']).points.mean()

country    province
Argentina  Mendoza Province    86.826593
           Other               86.001866
Armenia    Armenia             87.500000
Australia  Australia Other     85.518367
           New South Wales     87.694118
                                 ...
Uruguay    Juanico             86.333333
           Montevideo          88.272727
           Progreso            86.818182
           San Jose            84.000000
           Uruguay             86.833333
Name: points, Length: 425, dtype: float64

In [28]:
reviews.groupby(['country']).price.agg([len, min, max])

                            len   min     max
country
Argentina                3800.0   4.0   230.0
Armenia                     2.0  14.0    15.0
Australia                2329.0   5.0   850.0
Austria                  3345.0   7.0  1100.0
Bosnia and Herzegovina      2.0  12.0    13.0
Brazil                     52.0  10.0    60.0
Bulgaria                  141.0   8.0   100.0
Canada                    257.0  12.0   120.0
Chile                    4472.0   5.0   400.0
China                       1.0  18.0    18.0
Croatia                    73.0  12.0    65.0
Cyprus                     11.0  11.0    21.0
Czech Republic             12.0  15.0    45.0
Egypt                       1.0   NaN     NaN
England                    74.0  25.0    95.0
France                  22093.0   5.0  3300.0
Georgia                    86.0   9.0    40.0
Germany                  2165.0   5.0   775.0
Greece                    466.0   8.0    79.0
Hungary                   146.0  10.0   764.0
India                       9.0  10.0    20.0
Israel                    505.0   8.0   150.0
Italy                   19540.0   5.0   900.0
Lebanon                    35.0  13.0    75.0
Luxembourg                  6.0  16.0    30.0
Macedonia                  12.0  15.0    20.0
Mexico                     70.0   8.0   108.0
Moldova                    59.0   8.0    42.0
Morocco                    28.0  14.0    40.0
New Zealand              1419.0   7.0   130.0
Peru                       16.0  10.0    68.0
Portugal                 5691.0   5.0  1000.0
Romania                   120.0   4.0   320.0
Serbia                     12.0  15.0    42.0
Slovakia                    1.0  16.0    16.0
Slovenia                   87.0   7.0    90.0
South Africa             1401.0   5.0   330.0
Spain                    6645.0   4.0   770.0
Switzerland                 7.0  21.0   160.0
Turkey                     90.0  14.0   120.0
US                      54504.0   4.0  2013.0
Ukraine                    14.0   6.0    13.0
Uruguay                   109.0  10.0   130.0

In [29]:
reviews.groupby(['country', 'province']).price.agg([len, min, max])

                               len   min    max
country   province
Argentina Mendoza Province  3264.0   4.0  230.0
          Other              536.0   7.0  150.0
Armenia   Armenia              2.0  14.0   15.0
Australia Australia Other    245.0   5.0  130.0
          New South Wales     85.0   8.0  125.0
...                            ...   ...    ...
Uruguay   Juanico             12.0  10.0  130.0
          Montevideo          11.0  17.0   60.0
          Progreso            11.0  12.0   46.0
          San Jose             3.0  20.0   50.0
          Uruguay             24.0  12.0   50.0

[425 rows x 3 columns]

In [30]:
countries_reviewed = reviews.groupby(['country', 'province']).description.agg([len])
countries_reviewed

                             len
country   province
Argentina Mendoza Province  3264
          Other              536
Armenia   Armenia              2
Australia Australia Other    245
          New South Wales     85
...                          ...
Uruguay   Juanico             12
          Montevideo          11
          Progreso            11
          San Jose             3
          Uruguay             24

[425 rows x 1 columns]

In [31]:
mi = countries_reviewed.index
print(mi)
type(mi)

MultiIndex([('Argentina',  'Mendoza Province'),
            ('Argentina',             'Other'),
            (  'Armenia',           'Armenia'),
            ('Australia',   'Australia Other'),
            ('Australia',   'New South Wales'),
            ('Australia',   'South Australia'),
            ('Australia',          'Tasmania'),
            ('Australia',          'Victoria'),
            ('Australia', 'Western Australia'),
            (  'Austria',           'Austria'),
            ...
            (       'US',        'Washington'),
            (       'US', 'Washington-Oregon'),
            (  'Ukraine',           'Ukraine'),
            (  'Uruguay',         'Atlantida'),
            (  'Uruguay',         'Canelones'),
            (  'Uruguay',           'Juanico'),
            (  'Uruguay',        'Montevideo'),
            (  'Uruguay',          'Progreso'),
            (  'Uruguay',          'San Jose'),
            (  'Uruguay',           'Uruguay')],
           names=['country', 'province'], length=425)

pandas.core.indexes.multi.MultiIndex

In [32]:
countries_reviewed.reset_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
2      Armenia           Armenia     2
3    Australia   Australia Other   245
4    Australia   New South Wales    85
..         ...               ...   ...
420    Uruguay           Juanico    12
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

In [33]:
countries_reviewed = countries_reviewed.reset_index()
countries_reviewed.sort_values(by='len')

          country               province    len
179        Greece  Muscat of Kefallonian      1
192        Greece          Sterea Ellada      1
194        Greece                 Thraki      1
354  South Africa             Paardeberg      1
40         Brazil       Serra do Sudeste      1
..            ...                    ...    ...
409            US                 Oregon   5373
227         Italy                Tuscany   5897
118        France               Bordeaux   5941
415            US             Washington   8639
392            US             California  36247

[425 rows x 3 columns]

In [34]:
countries_reviewed.sort_values(by='len', ascending=False)

          country         province    len
392            US       California  36247
415            US       Washington   8639
118        France         Bordeaux   5941
227         Italy          Tuscany   5897
409            US           Oregon   5373
..            ...              ...    ...
101       Croatia              Krk      1
247   New Zealand        Gladstone      1
357  South Africa  Piekenierskloof      1
63          Chile          Coelemu      1
149        Greece           Beotia      1

[425 rows x 3 columns]

In [35]:
countries_reviewed.sort_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
2      Armenia           Armenia     2
3    Australia   Australia Other   245
4    Australia   New South Wales    85
..         ...               ...   ...
420    Uruguay           Juanico    12
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

In [36]:
countries_reviewed.sort_values(by=['country', 'len'])

       country          province   len
1    Argentina             Other   536
0    Argentina  Mendoza Province  3264
2      Armenia           Armenia     2
6    Australia          Tasmania    42
4    Australia   New South Wales    85
..         ...               ...   ...
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
420    Uruguay           Juanico    12
424    Uruguay           Uruguay    24
419    Uruguay         Canelones    43

[425 rows x 3 columns]

In [37]:
reviews.head(15)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel
9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam
10,US,"Soft, supple plum envelopes an oaky structure ...",Mountain Cuvée,87,19.0,California,Napa Valley,Napa,Virginie Boone,@vboone,Kirkland Signature 2011 Mountain Cuvée Caberne...,Cabernet Sauvignon,Kirkland Signature
11,France,"This is a dry wine, very spicy, with a tight, ...",NaN,87,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Leon Beyer 2012 Gewurztraminer (Alsace),Gewürztraminer,Leon Beyer
12,US,"Slightly reduced, this wine offers a chalky, t...",NaN,87,34.0,California,Alexander Valley,Sonoma,Virginie Boone,@vboone,Louis M. Martini 2012 Cabernet Sauvignon (Alex...,Cabernet Sauvignon,Louis M. Martini
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
14,US,Building on 150 years and six generations of w...,NaN,87,12.0,California,Central Coast,Central Coast,Matt Kettmann,@mattkettmann,Mirassou 2012 Chardonnay (Central Coast),Chardonnay,Mirassou

In [38]:
reviews_written = reviews.groupby('taster_twitter_handle').size()
reviews_written

taster_twitter_handle
@AnneInVino          3685
@JoeCz               5147
@bkfiona               27
@gordone_cellars     4177
@kerinokeefe        10776
@laurbuzz            1835
@mattkettmann        6332
@paulgwine           9532
@suskostrzewa        1085
@vboone              9537
@vossroger          25514
@wawinereport        4966
@wineschach         15134
@winewchristina         6
@worldwineguys       1005
dtype: int64

In [39]:
reviews_written = reviews.groupby('taster_twitter_handle').taster_twitter_handle.count()
reviews_written

taster_twitter_handle
@AnneInVino          3685
@JoeCz               5147
@bkfiona               27
@gordone_cellars     4177
@kerinokeefe        10776
@laurbuzz            1835
@mattkettmann        6332
@paulgwine           9532
@suskostrzewa        1085
@vboone              9537
@vossroger          25514
@wawinereport        4966
@wineschach         15134
@winewchristina         6
@worldwineguys       1005
Name: taster_twitter_handle, dtype: int64

In [40]:
best_rating_per_price = reviews.groupby('price').points.max()
best_rating_per_price

price
4.0       86
5.0       87
6.0       88
7.0       91
8.0       91
          ..
1900.0    98
2000.0    97
2013.0    91
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64

In [41]:
best_rating_per_price = reviews.groupby('price')['points'].max().sort_index()
best_rating_per_price

price
4.0       86
5.0       87
6.0       88
7.0       91
8.0       91
          ..
1900.0    98
2000.0    97
2013.0    91
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64

In [42]:
price_extremes=reviews.groupby('variety').price.agg(['min','max'])
price_extremes

              min    max
variety
Abouriou     15.0   75.0
Agiorgitiko  10.0   66.0
Aglianico     6.0  180.0
Aidani       27.0   27.0
Airen         8.0   10.0
...           ...    ...
Zinfandel     5.0  100.0
Zlahtina     13.0   16.0
Zweigelt      9.0   70.0
Çalkarası    19.0   19.0
Žilavka      15.0   15.0

[707 rows x 2 columns]

In [43]:
price_extremes=reviews.groupby('variety').price.agg(['min','max']).sort_values(by=['min','max'],ascending=False)
price_extremes

                                  min    max
variety
Ramisco                         495.0  495.0
Terrantez                       236.0  236.0
Francisa                        160.0  160.0
Rosenmuskateller                150.0  150.0
Tinta Negra Mole                112.0  112.0
...                               ...    ...
Roscetto                          NaN    NaN
Sauvignon Blanc-Sauvignon Gris    NaN    NaN
Tempranillo-Malbec                NaN    NaN
Vital                             NaN    NaN
Zelen                             NaN    NaN

[707 rows x 2 columns]

In [44]:
reviewer_mean_ratings = reviews.groupby('taster_name').points.mean()
reviewer_mean_ratings

taster_name
Alexander Peartree    85.855422
Anna Lee C. Iijima    88.415629
Anne Krebiehl MW      90.562551
Carrie Dykes          86.395683
Christina Pickard     87.833333
Fiona Adams           86.888889
Jeff Jenssen          88.319756
Jim Gordon            88.626287
Joe Czerwinski        88.536235
Kerin O’Keefe         88.867947
Lauren Buzzeo         87.739510
Matt Kettmann         90.008686
Michael Schachner     86.907493
Mike DeSimone         89.101167
Paul Gregutt          89.082564
Roger Voss            88.708003
Sean P. Sullivan      88.755739
Susan Kostrzewa       86.609217
Virginie Boone        89.213379
Name: points, dtype: float64

In [45]:
reviewer_mean_ratings.describe()

count    19.000000
mean     88.233026
std       1.243610
min      85.855422
25%      87.323501
50%      88.536235
75%      88.975256
max      90.562551
Name: points, dtype: float64

In [46]:
country_variety_counts=reviews.groupby(['country','variety']).variety.count().sort_values(ascending=False)
country_variety_counts

country    variety
US         Pinot Noir                  9885
           Cabernet Sauvignon          7315
           Chardonnay                  6801
France     Bordeaux-style Red Blend    4725
Italy      Red Blend                   3624
                                       ...
Uruguay    Tempranillo-Tannat             1
Italy      Pignolo                        1
           Muscat                         1
           Moscato di Noto                1
Argentina  Barbera                        1
Name: variety, Length: 1612, dtype: int64

In [47]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [48]:
reviews.price.dtype

dtype('float64')

In [49]:
reviews.dtypes

country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
dtype: object

In [50]:
reviews.points.astype('float64')

0         87.0
1         87.0
2         87.0
3         87.0
4         87.0
          ...
129966    90.0
129967    90.0
129968    90.0
129969    90.0
129970    90.0
Name: points, Length: 129971, dtype: float64

In [51]:
reviews.index.dtype

dtype('int64')

In [52]:
reviews[pd.isnull(reviews.country)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
913,NaN,"Amber in color, this wine has aromas of peach ...",Asureti Valley,87,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Gotsa Family Wines 2014 Asureti Valley Chinuri,Chinuri,Gotsa Family Wines
3131,NaN,"Soft, fruity and juicy, this is a pleasant, si...",Partager,83,NaN,NaN,NaN,NaN,Roger Voss,@vossroger,Barton & Guestier NV Partager Red,Red Blend,Barton & Guestier
4243,NaN,"Violet-red in color, this semisweet wine has a...",Red Naturally Semi-Sweet,88,18.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Kakhetia Traditional Winemaking 2012 Red Natur...,Ojaleshi,Kakhetia Traditional Winemaking
9509,NaN,This mouthwatering blend starts with a nose of...,Theopetra Malagouzia-Assyrtiko,92,28.0,NaN,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Tsililis 2015 Theopetra Malagouzia-Assyrtiko W...,White Blend,Tsililis
9750,NaN,This orange-style wine has a cloudy yellow-gol...,Orange Nikolaevo Vineyard,89,28.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Ross-idi 2015 Orange Nikolaevo Vineyard Chardo...,Chardonnay,Ross-idi
...,...,...,...,...,...,...,...,...,...,...,...,...,...
124176,NaN,This Swiss red blend is composed of four varie...,Les Romaines,90,30.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Les Frères Dutruy 2014 Les Romaines Red,Red Blend,Les Frères Dutruy
129407,NaN,Dry spicy aromas of dusty plum and tomato add ...,Reserve,89,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Cabernet Sauvignon,Cabernet Sauvignon,El Capricho
129408,NaN,El Capricho is one of Uruguay's more consisten...,Reserve,89,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Tempranillo,Tempranillo,El Capricho
129590,NaN,"A blend of 60% Syrah, 30% Cabernet Sauvignon a...",Shah,90,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Büyülübağ 2012 Shah Red,Red Blend,Büyülübağ
129900,NaN,This wine offers a delightful bouquet of black...,NaN,91,32.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Psagot 2014 Merlot,Merlot,Psagot

In [53]:
reviews.region_2.fillna("Unknown")

0                   Unknown
1                   Unknown
2         Willamette Valley
3                   Unknown
4         Willamette Valley
                ...
129966              Unknown
129967         Oregon Other
129968              Unknown
129969              Unknown
129970              Unknown
Name: region_2, Length: 129971, dtype: object

In [54]:
reviews.taster_twitter_handle.replace("@kerinokeefe", "@kerino")

0             @kerino
1          @vossroger
2         @paulgwine
3                 NaN
4         @paulgwine
             ...
129966            NaN
129967    @paulgwine
129968     @vossroger
129969     @vossroger
129970     @vossroger
Name: taster_twitter_handle, Length: 129971, dtype: object

In [68]:
dtype1 = reviews['points'].dtype
dtype1

dtype('int64')

In [69]:
point_strings = reviews.points.astype(str)
point_strings

0         87
1         87
2         87
3         87
4         87
          ..
129966    90
129967    90
129968    90
129969    90
129970    90
Name: points, Length: 129971, dtype: object

In [66]:
pd.isnull(reviews.price)

0          True
1         False
2         False
3         False
4         False
          ...
129966    False
129967    False
129968    False
129969    False
129970    False
Name: price, Length: 129971, dtype: bool

In [67]:
pd.isnull(reviews.price).sum()

8996

In [58]:
missing_price_reviews = reviews[reviews.price.isnull()]
n_missing_prices = len(missing_price_reviews)
# Cute alternative solution: if we sum a boolean series, True is treated as 1 and False as 0
n_missing_prices = reviews.price.isnull().sum()
# or equivalently:
n_missing_prices = pd.isnull(reviews.price).sum()
n_missing_prices

8996

In [77]:
# reviews['region_1'].fillna('Unknown')
reviews_per_region = reviews.fillna('Unknown').groupby('region_1')['region_1'].count().sort_values(ascending=False)
reviews_per_region

region_1
Unknown                              21247
Napa Valley                           4480
Columbia Valley (WA)                  4124
Russian River Valley                  3091
California                            2629
                                     ...
Mount Barker & Margaret River            1
Murray-Darling                           1
Muscat de Saint-Jean de Minervois        1
Canada                                   1
Massachusetts                            1
Name: region_1, Length: 1230, dtype: int64

In [78]:
reviews_per_region=reviews.region_1.fillna('Unknown').value_counts().sort_values(ascending=False)
reviews_per_region

Unknown                         21247
Napa Valley                      4480
Columbia Valley (WA)             4124
Russian River Valley             3091
California                       2629
                                ...
McLaren Vale-Langhorne Creek        1
Cabernet de Saumur                  1
Mâcon-Mancey                        1
Altos de Mendoza                    1
Dolcetto d'Alba Superiore           1
Name: region_1, Length: 1230, dtype: int64

In [79]:
reviews.rename(columns={'points': 'score'})

,country,description,designation,score,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [81]:
reviews.rename(index={0: 'firstEntry', 1: 'secondEdit'})

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
firstEntry,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
secondEdit,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [82]:
reviews.rename_axis("wines", axis='rows').rename_axis("fields", axis='columns')

fields,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
wines,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [3]:
canadian_youtube_path=r"C:\Users\gokul\Downloads\xdm\datasample\CAvideos.csv"
british_youtube_path=r"C:\Users\gokul\Downloads\xdm\datasample\INvideos.csv"
canadian_youtube = pd.read_csv(canadian_youtube_path)
british_youtube = pd.read_csv(british_youtube_path)

pd.concat([canadian_youtube, british_youtube])

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37347,iNHecA3PJCo,18.14.06,फेकू आशिक़ - राजस्थान की सबसे शानदार कॉमेडी | ...,RDC Rajasthani,23,2018-06-13T08:01:11.000Z,"twinkle vaishnav comedy|""twinkle vaishnav""|""tw...",214378,3291,404,196,https://i.ytimg.com/vi/iNHecA3PJCo/default.jpg,False,False,False,PRG Music & RDC Rajasthani presents फेकू आशिक़...
37348,dpPmPbhcslM,18.14.06,Seetha | Flowers | Ep# 364,Flowers TV,24,2018-06-13T11:30:04.000Z,"flowers serials|""actress""|""malayalam serials""|...",406828,1726,478,1428,https://i.ytimg.com/vi/dpPmPbhcslM/default.jpg,False,False,False,"Flowers - A R Rahman Show,Book your Tickets He..."
37349,mV6aztP58f8,18.14.06,Bhramanam I Episode 87 - 12 June 2018 I Mazhav...,Mazhavil Manorama,24,2018-06-13T05:00:02.000Z,"mazhavil manorama|""bhramanam full episode""|""gt...",386319,1216,453,697,https://i.ytimg.com/vi/mV6aztP58f8/default.jpg,False,False,False,Subscribe to Mazhavil Manorama now for your da...
37350,qxqDNP1bDEw,18.14.06,Nua Bohu | Full Ep 285 | 13th June 2018 | Odia...,Tarang TV,24,2018-06-13T15:07:49.000Z,"tarang|""tarang tv""|""tarang tv online""|""tarang ...",130263,698,115,65,https://i.ytimg.com/vi/qxqDNP1bDEw/default.jpg,False,False,False,Nuabohu : Story of a rustic village girl who w...
37351,wERgpPK44w0,18.14.06,Ee Nagaraniki Emaindi Trailer | Tharun Bhascke...,Suresh Productions,24,2018-06-10T04:29:54.000Z,"Ee Nagaraniki Emaindi|""Ee Nagaraniki Emaindi T...",1278249,22466,1609,1205,https://i.ytimg.com/vi/wERgpPK44w0/default.jpg,False,False,False,Check out Ee Nagaraniki Emaindi Trailer #EeNag...

In [4]:
left = canadian_youtube.set_index(['title', 'trending_date'])
right = british_youtube.set_index(['title', 'trending_date'])

left.join(right, lsuffix='_CAN', rsuffix='_UK')

                                                                 video_id_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       PNn8sECd7io
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       DvPW66IFhMI
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       EXEaMjFeiEk
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       bYvQmusLaxw
                                                   17.21.12       bYvQmusLaxw
...                                                                       ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       WttN1Z0XF4k
                                                   18.29.04       WttN1Z0XF4k
                                                   18.30.04       WttN1Z0XF4k
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       Wt9Gkpmbt44
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       Az72jrKbANA

                                                                                channel_title_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                            Markiplier
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                        AlexRamiGaming
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                        AlexRamiGaming
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                  Pure Living for Life
                                                   17.21.12                  Pure Living for Life
...                                                                                           ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                          How Talented
                                                   18.29.04                          How Talented
                                                   18.30.04                          How Talented
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                         TheBigJackpot
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       Right Side Broadcasting Network

                                                                  category_id_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                    20
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                    20
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                    20
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                    24
                                                   17.21.12                    24
...                                                                           ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                    24
                                                   18.29.04                    24
                                                   18.30.04                    24
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                    24
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                    25

                                                                          publish_time_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       2018-01-03T19:33:53.000Z
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       2018-03-09T07:15:52.000Z
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       2018-03-10T06:26:17.000Z
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       2017-12-20T02:49:11.000Z
                                                   17.21.12       2017-12-20T02:49:11.000Z
...                                                                                    ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       2018-04-28T19:40:58.000Z
                                                   18.29.04       2018-04-28T19:40:58.000Z
                                                   18.30.04       2018-04-28T19:40:58.000Z
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       2018-05-07T06:58:59.000Z
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       2018-04-03T23:12:37.000Z

                                                                                                           tags_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       getting over it|"markiplier"|"funny moments"|"...
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       PS4 Battle Royale|"PS4 Pro Battle Royale"|"Bat...
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       PS4 Battle Royale|"PS4 Pro Battle Royale"|"Bat...
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       timber frame|"timber framing"|"timber frame ra...
                                                   17.21.12       timber frame|"timber framing"|"timber frame ra...
...                                                                                                             ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       bgt|"bgt 2018"|"britain got talent"|"britain´s...
                                                   18.29.04       bgt|"bgt 2018"|"britain got talent"|"britain´s...
                                                   18.30.04       bgt|"bgt 2018"|"britain got talent"|"britain´s...
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       Slot Machine|"win"|"Gambling"|"Big Win"|"raja"...
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       YouTube shooter|"YouTube active shooter"|"acti...

                                                                  views_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01          835930
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03          212838
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03          200764
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12           79152
                                                   17.21.12          232762
...                                                                     ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05          713400
                                                   18.29.04          231906
                                                   18.30.04          476253
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05           28973
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04          103513

                                                                  likes_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01           47058
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03            5199
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03            5620
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12            7761
                                                   17.21.12           15515
...                                                                     ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05            4684
                                                   18.29.04            1924
                                                   18.30.04            3417
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05            2167
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04            1722

                                                                  dislikes_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01               1023
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                542
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                537
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                159
                                                   17.21.12                329
...                                                                        ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                260
                                                   18.29.04                 78
                                                   18.30.04                176
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                175
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                181

                                                                  comment_count_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                    8250
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                      11
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                      45
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                    1965
                                                   17.21.12                    3601
...                                                                             ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                     266
                                                   18.29.04                     146
                                                   18.30.04                     240
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                      10
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                      76

                                                                                              thumbnail_link_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       https://i.ytimg.com/vi/PNn8sECd7io/default.jpg
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       https://i.ytimg.com/vi/DvPW66IFhMI/default.jpg
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       https://i.ytimg.com/vi/EXEaMjFeiEk/default.jpg
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       https://i.ytimg.com/vi/bYvQmusLaxw/default.jpg
                                                   17.21.12       https://i.ytimg.com/vi/bYvQmusLaxw/default.jpg
...                                                                                                          ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       https://i.ytimg.com/vi/WttN1Z0XF4k/default.jpg
                                                   18.29.04       https://i.ytimg.com/vi/WttN1Z0XF4k/default.jpg
                                                   18.30.04       https://i.ytimg.com/vi/WttN1Z0XF4k/default.jpg
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       https://i.ytimg.com/vi/Wt9Gkpmbt44/default.jpg
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       https://i.ytimg.com/vi/Az72jrKbANA/default.jpg

                                                                  ...  \
title                                              trending_date  ...
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       ...
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       ...
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       ...
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       ...
                                                   17.21.12       ...
...                                                               ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       ...
                                                   18.29.04       ...
                                                   18.30.04       ...
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       ...
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       ...

                                                                  tags_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01           NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03           NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03           NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12           NaN
                                                   17.21.12           NaN
...                                                                   ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05           NaN
                                                   18.29.04           NaN
                                                   18.30.04           NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05           NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04           NaN

                                                                  views_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01            NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03            NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03            NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12            NaN
                                                   17.21.12            NaN
...                                                                    ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05            NaN
                                                   18.29.04            NaN
                                                   18.30.04            NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05            NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04            NaN

                                                                  likes_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01            NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03            NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03            NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12            NaN
                                                   17.21.12            NaN
...                                                                    ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05            NaN
                                                   18.29.04            NaN
                                                   18.30.04            NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05            NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04            NaN

                                                                 dislikes_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01              NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03              NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03              NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12              NaN
                                                   17.21.12              NaN
...                                                                      ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05              NaN
                                                   18.29.04              NaN
                                                   18.30.04              NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05              NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04              NaN

                                                                 comment_count_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                   NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                   NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                   NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                   NaN
                                                   17.21.12                   NaN
...                                                                           ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                   NaN
                                                   18.29.04                   NaN
                                                   18.30.04                   NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                   NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                   NaN

                                                                 thumbnail_link_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                    NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                    NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                    NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                    NaN
                                                   17.21.12                    NaN
...                                                                            ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                    NaN
                                                   18.29.04                    NaN
                                                   18.30.04                    NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                    NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                    NaN

                                                                  comments_disabled_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                        NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                        NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                        NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                        NaN
                                                   17.21.12                        NaN
...                                                                                ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                        NaN
                                                   18.29.04                        NaN
                                                   18.30.04                        NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                        NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                        NaN

                                                                 ratings_disabled_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                      NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                      NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                      NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                      NaN

In [5]:
renamed_reviews = reviews.rename(columns={'region_1': 'region','region_2':'locale'})
renamed_reviews

,country,description,designation,points,price,province,region,locale,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [6]:
reindexed = reviews.rename_axis('axis',axis=1)
reindexed

axis,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [7]:
reindexed = reviews.rename_axis('axis',axis='rows')
reindexed

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
axis,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [9]:
gaming_products_path=r"C:\Users\gokul\Downloads\xdm\datasample\top-things\reddits\g\gaming.csv"
movie_products_path=r"C:\Users\gokul\Downloads\xdm\datasample\top-things\reddits\m\movies.csv"

In [11]:
gaming_products = pd.read_csv(gaming_products_path)
gaming_products['subreddit'] = "r/gaming"
gaming_products

,name,category,amazon_link,total_mentions,subreddit_mentions,subreddit
0,BOOMco Halo Covenant Needler Blaster,Toys & Games,https://www.amazon.com/BOOMco-Halo-Covenant-Ne...,4.0,4,r/gaming
1,Raspberry PI 3 Model B 1.2GHz 64-bit quad-core...,Electronics,https://www.amazon.com/Raspberry-Model-A1-2GHz...,19.0,3,r/gaming
2,CanaKit 5V 2.5A Raspberry Pi 3 Power Supply / ...,Electronics,https://www.amazon.com/CanaKit-Raspberry-Suppl...,7.0,3,r/gaming
3,Panasonic K-KJ17MCA4BA Advanced Individual Cel...,Electronics,https://www.amazon.com/Panasonic-Advanced-Indi...,29.0,2,r/gaming
4,Mayflash GameCube Controller Adapter for Wii U...,Electronics,https://www.amazon.com/GameCube-Controller-Ada...,24.0,2,r/gaming
...,...,...,...,...,...,...
488,Chrono Trigger: Original Sound Version,CDs & Vinyl,https://www.amazon.com/Chrono-Trigger-Original...,1.0,1,r/gaming
489,Canon XA10 Professional Camcorder with 64GB In...,Electronics,https://www.amazon.com/Canon-Professional-Camc...,1.0,1,r/gaming
490,Made to Kill: A Ray Electromatic Mystery (Ray ...,Books,https://www.amazon.com/Made-Kill-Novel-L-Trilo...,1.0,1,r/gaming
491,Xbox 360 - Chatpad,Video Games,https://www.amazon.com/Microsoft-Xbox-360-Chat...,1.0,1,r/gaming
492,Project Arcade: Build Your Own Arcade Machine.,Books,https://www.amazon.com/Project-Arcade-Build-Yo...,1.0,1,r/gaming

In [12]:
movie_products = pd.read_csv(movie_products_path)
movie_products['subreddit'] = "r/movies"
movie_products

,name,category,amazon_link,total_mentions,subreddit_mentions,subreddit
0,Marvel Cinematic Universe: Phase One - Avenger...,Movies & TV,https://www.amazon.com/Marvel-Cinematic-Univer...,4.0,3,r/movies
1,On Stranger Tides,Books,https://www.amazon.com/Stranger-Tides-Tim-Powe...,3.0,3,r/movies
2,"Superintelligence: Paths, Dangers, Strategies",Books,https://www.amazon.com/Superintelligence-Dange...,7.0,2,r/movies
3,The Secret History of Star Wars,Books,https://www.amazon.com/Secret-History-Star-War...,4.0,2,r/movies
4,2D Glasses 4 Pack - Turns 3D movies back into ...,Electronics,https://www.amazon.com/gp/product/B00K9E7GCC,3.0,2,r/movies
...,...,...,...,...,...,...
298,Welcome to Night Vale CD: A Novel,Books,https://www.amazon.com/Welcome-Night-Vale-CD-N...,1.0,1,r/movies
299,Ran (StudioCanal Collection) [Blu-ray],Movies & TV,https://www.amazon.com/StudioCanal-Collection-...,1.0,1,r/movies
300,The Art of John Alvin,Books,https://www.amazon.com/Art-John-Alvin-Andrea/d...,1.0,1,r/movies
301,Apocalypto [Blu-ray],Movies & TV,https://www.amazon.com/Apocalypto-Blu-ray-Rudy...,1.0,1,r/movies
302,Cinelinx: A Card Game for People Who Love Movi...,Toys & Games,https://www.amazon.com/Cinelinx-Card-Game-Peop...,1.0,1,r/movies

In [13]:
pd.concat([gaming_products,movie_products])

,name,category,amazon_link,total_mentions,subreddit_mentions,subreddit
0,BOOMco Halo Covenant Needler Blaster,Toys & Games,https://www.amazon.com/BOOMco-Halo-Covenant-Ne...,4.0,4,r/gaming
1,Raspberry PI 3 Model B 1.2GHz 64-bit quad-core...,Electronics,https://www.amazon.com/Raspberry-Model-A1-2GHz...,19.0,3,r/gaming
2,CanaKit 5V 2.5A Raspberry Pi 3 Power Supply / ...,Electronics,https://www.amazon.com/CanaKit-Raspberry-Suppl...,7.0,3,r/gaming
3,Panasonic K-KJ17MCA4BA Advanced Individual Cel...,Electronics,https://www.amazon.com/Panasonic-Advanced-Indi...,29.0,2,r/gaming
4,Mayflash GameCube Controller Adapter for Wii U...,Electronics,https://www.amazon.com/GameCube-Controller-Ada...,24.0,2,r/gaming
...,...,...,...,...,...,...
298,Welcome to Night Vale CD: A Novel,Books,https://www.amazon.com/Welcome-Night-Vale-CD-N...,1.0,1,r/movies
299,Ran (StudioCanal Collection) [Blu-ray],Movies & TV,https://www.amazon.com/StudioCanal-Collection-...,1.0,1,r/movies
300,The Art of John Alvin,Books,https://www.amazon.com/Art-John-Alvin-Andrea/d...,1.0,1,r/movies
301,Apocalypto [Blu-ray],Movies & TV,https://www.amazon.com/Apocalypto-Blu-ray-Rudy...,1.0,1,r/movies
302,Cinelinx: A Card Game for People Who Love Movi...,Toys & Games,https://www.amazon.com/Cinelinx-Card-Game-Peop...,1.0,1,r/movies

powerlifting_meets = pd.read_csv("../input/powerlifting-database/meets.csv")
powerlifting_competitors = pd.read_csv("../input/powerlifting-database/openpowerlifting.csv")


## Both tables include references to a `MeetID`, a unique key for each meet (competition) included in the database. Using this, generate a dataset combining the two tables into one.

powerlifting_combined = powerlifting_combined = powerlifting_meets.set_index("MeetID").join(powerlifting_competitors.set_index("MeetID"))